### ISSUE TITLE
Support ENV Vars on landofile

### ISSUE THREAD

**Issue by igasi** [lando/core#218]
As a lando user who works with Drupal sites and multisites, I want to be able to use Environment Variables in .lando.yml files, in order to have names or services dynamics. This feature is already support by docker-compose file, and it would be nice to have in .lando files.

In the definition of landofile we are able to add env_file, and having the feature to read that variables to use inside the landofile could be helpful for manage drupal multisite, without necesite to all multisites all the same time if we don't need, this also helps to optimize resource s for own computers.

Example

```
# .lando.yml
name: ${PROJECT_NAME}
recipe: drupal8
config:
  webroot: ${DOCROOT_PATH}
services:
  appserver:
    xdebug: true
env_file:
  - .env
```

Setting .env file for site1
```
# .env
PROJECT_NAME=site1
DOCROOT_PATH=./docroot
```

Setting .env file for site2
```
# .env
PROJECT_NAME=site2
DOCROOT_PATH=./sites/site2
```

Right now, I have to declare many database services that I really don't need because I only want to work on 1 site at once. Another way edit the landofile and change as I required, but landofile is versioned could be potencially bad idea to modify the file because we could commit this change, If we use env vars using .env file that should not under version control, we avoid many issues like this and we are implementing one of the best practices of 12FactorApp related to configuration.

Actually this feature is currently usable on docker-compose files, in the same way that my example, as a landofile is a wrapper to manage docker-compose definitions seems like this feature should be available to have a better support of docker-compose.

Development approach suggestion:
If JS-YAML package does not support read env var, we should add another parser to check the file and replace it using a regex code, then use this parsed file.

**Comment by almunnings** [comment]
Any uh, promises here?
Been hanging out for this for years!

**Comment by AaronFeledy** [comment]
I think the original use case in this issue is satisfied by Lando's [local override](https://docs.lando.dev/core/v3/#override-file) or by using base/upstream landofiles, also mentioned on that page.

@almunnings What's your use case for such a feature? It may already be possible.

**Comment by almunnings** [comment]
Use case is templating repos for me. Have about 45 active sites and a mishmash of .env. Id prefer to advise people to change one variable vs rewrite several and update urls.

Being able to control the project name is the big one. But also to be able to reference variables within the yaml itself, creating reusable snippets. 

For instance, some tooling in yaml (custom drush command, api actions, whatever) might want to get the lando project url distinctly as an argument in a command, without wanting to duplicate the domain and project name multiple times.

I'm sure other people have usage too.

**Comment by AaronFeledy** [comment]
Generally, Lando should be templated with a `.lando.base.yml` or a `.lando.upstream.yml` file that has all the common lando config but no name set. Then you can add a minimal `.lando.yml` with just the name key set, and any other additions or overrides specific to this app. This will be merged onto the base landofile.

For tooling you can use environment variables that are present inside the service container and you can set your own. Even by passing a variable at build time. This base file does some various variable things:

`.lando.base.yml`
```yaml
services:
  appserver:
    type: php
    overrides:
      environment:
        - MY_PATH=my-path
        - MY_VAR=${INPUT:-"No input"}
    build:
      - echo $MY_VAR

tooling:
  url1:
    service: appserver
    cmd: "echo http://$LANDO_APP_PROJECT.$LANDO_DOMAIN/$MY_PATH"

  url2:
    env:
      MY_PATH: "other-path"
    service: appserver
    cmd: "echo http://$LANDO_APP_PROJECT.$LANDO_DOMAIN/$MY_PATH"
```
After adding your `.lando.yml` next to this one, you can `INPUT="My custom message" lando start` to set the `MY_VAR` variable inside the container. Note that variables passed into the build like this need to be passed in every time the app is built or rebuilt.
