### ISSUE TITLE
Adding ssl to services phpmyadmin and mailhog enables but shows errors

### ISSUE THREAD

**Issue by yorkshire-pudding** [lando/core#230]
**Steps to reproduce**

1. Add PHPMyAdmin and Mailhog services to recipe
2. Add `ssl: true` to the `services: phpmyadmin` section and `services: mailhog` section
3. `lando rebuild -y`

**Expected result**
https is enabled on both with 200 result in check and no errors

**Actual result**
https is enabled on both with 200 result but receive errors:

  ✔ APPSERVER URLS
     ✔ http://site.lndo.site/ [200]
     ✔ https://site.lndo.site/ [200]
     ✔ https://localhost:28670 [200]
     ✔ http://localhost:28671 [200]
  ⚠ PHPMYADMIN URLS
     ✔ http://db.site.lndo.site/ [200]
     ✔ https://db.site.lndo.site/ [200]
     ✖ write EPROTO 00D88008BB7F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version
       number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
     ✔ http://localhost:28663 [200]
  ⚠ MAILHOG URLS
     ✔ http://mail.site.lndo.site/ [200]
     ✔ https://mail.site.lndo.site/ [200]
     ✖ Client network socket disconnected before secure TLS connection was established
     ✔ http://localhost:28667 [200]

If I don't include the `ssl: true` lines then I can't access on https and the check for those lines returns 404.

```yaml
services:
  phpmyadmin:
    type: phpmyadmin
    hosts: database
    ssl: true
  mailhog:
    type: mailhog
    hosts: mailhog
    ssl: true
    hogfrom:
      - appserver
 ```
