### ISSUE TITLE
TypeError: Cannot convert undefined or null to object when empty options are set in a command under tooling

### ISSUE THREAD

**Issue by kaszarobert** [lando/core#240]
Just updated to v3.22.3 and I noticed one regression in the Landofile when specifying custom commands under tooling. This was valid before:

```
tooling:
  phpcs:
    service: appserver
    cmd: "/app/vendor/bin/phpcs --standard=Drupal,DrupalPractice --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md"
    options:
    description: Run phpcs for given folder or file.
  phpcbf:
    service: appserver
    cmd: "/app/vendor/bin/phpcbf --standard=Drupal,DrupalPractice --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md"
    options:
    description: Run phpcs for given folder or file.
```

But now, it throws an error until I remove the line with the empty options:

```
/snapshot/cli/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at builder (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/build/lib/command.js:152:35)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/build/lib/yargs.js:986:25)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)

Node.js v18.19.1
```

The documentation page also shows examples where it seems an empty option key is valid:
https://docs.lando.dev/core/v3/tooling.html#usage
https://docs.lando.dev/core/v3/tooling.html#overriding
