### ISSUE TITLE
COLUMNS is set to 80 rather than terminal width

### ISSUE THREAD

**Issue by yorkshire-pudding** [lando/core#272]
I thought from https://github.com/lando/lando/issues/1847 that Lando would get columns from the terminal.
I am running Ubuntu 24.04.1 LTS within WSL2 using Windows Terminal

Docker version:

```shell
$ docker --version
Docker version 27.3.1, build ce12230
```

If I do: 

```yaml
services:
  appserver:
    overrides:
      environment:
        COLUMNS: "140"
```

then it picks it up and works fine, but if not, it is stuck at `80`, which IMHO is worse than the `256` it was
