### ISSUE TITLE
Add support for running against a local docker image.

### ISSUE THREAD

**Issue by codebymikey** [lando/core#31]
When trying to test lando against a locally built image, it makes an attempt to call [`docker-compose pull`](https://github.com/lando/core/blob/c7bf572/lib/router.js#L33-L34) to pull, but crashes because the docker image doesn't exist in an upstream repo.

We should probably be building with [`docker-compose build --pull`](https://github.com/lando/core/blob/c7bf572/lib/compose.js#L80) instead rather than have it as two separate commands (it's probably more performant too).

---

Example `.lando.yml` file:

```yaml
# file: .lando.yml
name: docker-test
services:
  test:
    type: compose
    app_mount: delegated
    overrides:
      # This image only exists locally for now, so Lando should be able to use it just fine.
      image: docker-test/only-locally-available
      command: tail -f /dev/null
```
