### ISSUE TITLE
depends_on not woring in v4 l337 service

### ISSUE THREAD

**Issue by kinglouie** [lando/core#340]
I tried running the custom zitadel docker image `ghcr.io/zitadel/zitadel:latest` alongside the lando `postgres` plugin.
The zitadel container should only start when the postgres server is ready, so i added the db container to the `depends_on` key with `condition: service_healthy`. On `lando start` lando errors with `container sso_db-sso_1 has no healthcheck configured` although the postgres plugin has a healthcheck configured.

This is my complete lando.yml
```
name: sso

services:
  db-sso:
    type: postgres:16
    portforward: true

  sso:
    api: 4
    type: l337
    image: "ghcr.io/zitadel/zitadel:latest"
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    ports:
      - 80/http
    environment:
      ZITADEL_DATABASE_POSTGRES_HOST: db-sso
      ZITADEL_DATABASE_POSTGRES_PORT: 5432
      ZITADEL_DATABASE_POSTGRES_DATABASE: database
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD:
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable
      ZITADEL_EXTERNALPORT: 80
      ZITADEL_PORT: 80
      ZITADEL_EXTERNALSECURE: false
      ZITADEL_TLS_ENABLED: false
      ZITADEL_EXTERNALDOMAIN: sso.lndo.site
    depends_on:
      db-sso:
        condition: service_healthy

proxy:
  sso:
    - hostname: sso.lndo.site
```

how can I ensure that db is ready for custom services?

Lando version: v3.23.14

**Comment by pirog** [comment]
@kinglouie thanks for trying L337 out! 

Let me look into this but i think i understand why this is happening.

**Comment by pirog** [comment]
@kinglouie i think this i actually working as expected. The `postgres:16` lando service does not actually implement a docker healthcheck, it implements a special "lando" one. However, i think you can do what you want with this:

```yaml
services:
  db-sso:
    type: postgres:16
    portforward: true
    overrides:
      healthcheck:
        test: some-healthcheck-command

  sso:
    api: 4
    type: l337
    image: "ghcr.io/zitadel/zitadel:latest"
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    ports:
      - 80/http
    environment:
      ZITADEL_DATABASE_POSTGRES_HOST: db-sso
      ZITADEL_DATABASE_POSTGRES_PORT: 5432
      ZITADEL_DATABASE_POSTGRES_DATABASE: database
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD:
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable
      ZITADEL_EXTERNALPORT: 80
      ZITADEL_PORT: 80
      ZITADEL_EXTERNALSECURE: false
      ZITADEL_TLS_ENABLED: false
      ZITADEL_EXTERNALDOMAIN: sso.lndo.site
    depends_on:
      db-sso:
        condition: service_healthy
```

**Comment by kinglouie** [comment]
@pirog Thanks for looking into this, at the time I created this issue I came to the same solution you provided after reading how the lando services are built.

I think the docs could make this a little more clear that the healthcheck that lando provides is not the same as the docker one. At first I tried creating a healthcheck according to the docs [here](https://docs.lando.dev/config/healthcheck.html) but this did not work when you conbine it with the `depends_on` function. I am really confused what is exactly the point of defining a custom lando healthcheck when it can not be used by other services to depend on?

**Comment by pirog** [comment]
Thanks for the feedback. 

Lando is not the same thing as docker, although it does currently use some _docker things_ under the hood. I'm guessing the confusion is mostly around the `L337` service which is the lowest level of our new fourth generation services and does very explicitly adopt and support both dockerfile and docker compose _syntax_ although we dont guarantee it will produce the same results. The other Lando services you are using are older generation 3 services which are still the "default" and "stable" services and do not map directly to docker compose things unless you are using that `overrides` key. 

The Gen 3 and Gen 4 services don't play perfectly with one another and im guessing it would be a not great use of engineering time to see that they do. 

Lando Gen 3 services implement a different healthcheck mechanism because we don't want to have the healthcheck poll indefinitely on a users computer. Our healthcheck just runs when you start up an app to tell you a service booted as expected.

We are planning to do a pretty extensive update to the docs when we officially launch the Gen 4 stuff.

**Comment by kinglouie** [comment]
Thank you very much for clearing that up for me!

> Lando Gen 3 services implement a different healthcheck mechanism because we don't want to have the healthcheck poll indefinitely on a users computer. Our healthcheck just runs when you start up an app to tell you a service booted as expected.

That seems pretty sensible to me. I was just a little confused because I ran into issues with services not starting in the correct order and found no way to control this within the lando docs. 

It would be really nice if lando would provide a custom service option to use the lando style healthchecks for other lando services to depend on. I use lando a lot for node dev where I need `depends_on` with a healthy database service all the time.
At the moment with v3 services the .lando.yml is really verbose:

```
services:
  db:
    type: postgres:16
    overrides:
      healthcheck:
        test: pg_isready -p 5432 -h localhost -d database -U postgres
        interval: 5s
        timeout: 30s
        retries: 10

  app:
    type: node
    command: some-command-that-needs-db-to-be-up
    overrides:
      depends_on:
        db:
          condition: service_healthy
```

with a custom lando service option that maybe already implies using the `services_healthy` instead of `service_started`  this could be reduced to this:

```
services:
  db:
    type: postgres:16

  app:
    type: node
    command: some-command-that-needs-db-to-be-up
    depends_on: db
```

what are your thoughts on this?
