### ISSUE TITLE
Can't connect Wordpress Vite with lando

### ISSUE THREAD

**Issue by YevheniiVolosiuk** [lando/core#358]
How to make it work altogether?

lando config
```{ service: 'appserver',
    urls:
     [ 'http://lando-wordpress.lndo.site/',
       'https://lando-wordpress.lndo.site/',
       'http://localhost:44475' ],
    type: 'wordpress-php',
    healthy: 'unknown',
    via: 'apache',
    webroot: 'public/web',
    config: { php: '/home/yevhenii/.lando/config/wordpress/php.ini' },
    version: '8.4',
    meUser: 'www-data',
    hasCerts: true,
    api: 3,
    hostnames: [ 'appserver.landowordpress.internal' ],
    hostname: [] },
  { service: 'database',
    urls: [],
    type: 'mariadb',
    healthy: 'unknown',
    internal_connection: { host: 'database', port: '3306' },
    external_connection: { host: '127.0.0.1', port: '44472' },
    healthcheck:
     'mysql --host=database --user=wordpress --database=wordpress --password=password --silent --execute "SHOW TABLES;"',
    creds: { database: 'wordpress', password: 'password', user: 'wordpress' },
    config: { database: '/home/yevhenii/.lando/config/wordpress/mysql.cnf' },
    version: '11.5',
    meUser: 'www-data',
    hasCerts: false,
    api: 3,
    hostnames: [ 'database.landowordpress.internal' ],
    hostname: [] },
  { service: 'node',
    urls: [],
    type: 'node',
    healthy: 'unknown',
    config: {},
    version: '22',
    meUser: 'node',
    hasCerts: true,
    api: 3,
    hostnames: [ 'node.landowordpress.internal' ],
    hostname: [] },
  { service: 'redis',
    urls: [],
    type: 'redis',
    healthy: 'unknown',
    internal_connection: { host: 'redis', port: '6379' },
    external_connection: { host: '127.0.0.1', port: '6379' },
    config: {},
    version: '6',
    meUser: 'www-data',
    hasCerts: false,
    api: 3,
    hostnames: [ 'redis.landowordpress.internal' ],
    hostname: [] },
  { service: 'mailhog',
    urls:
     [ 'http://mail.lando-wordpress.lndo.site/',
       'https://mail.lando-wordpress.lndo.site/',
       'http://localhost:44474' ],
    type: 'mailhog',
    healthy: 'unknown',
    hogfrom: [ 'appserver' ],
    internal_connection: { host: 'mailhog', port: '1025' },
    external_connection: { host: '127.0.0.1', port: '44473' },
    config: {},
    version: 'v1.0.1',
    meUser: 'mailhog',
    hasCerts: true,
    api: 3,
    hostnames: [ 'mailhog.landowordpress.internal' ],
    hostname: [] },
  { service: 'phpmyadmin',
    urls:
     [ 'http://pma.lando-wordpress.lndo.site/',
       'https://pma.lando-wordpress.lndo.site/',
       'http://localhost:44476' ],
    type: 'phpmyadmin',
    healthy: 'unknown',
    backends: [ 'database' ],
    config: {},
    version: '5.2',
    meUser: 'www-data',
    hasCerts: true,
    api: 3,
    hostnames: [ 'phpmyadmin.landowordpress.internal' ],
    hostname: [] } ]
```
lando.yml
```
name: lando-wordpress
recipe: wordpress
proxy:
    appserver:
      - lando-wordpress.lndo.site
    phpmyadmin:
      - pma.lando-wordpress.lndo.site
    mailhog:
      - mail.lando-wordpress.lndo.site
#    node:
#      - vite.lando-wordpress.lndo.site:5173

config:
  php: '8.4'
  composer_version: "2.8.6"
  webroot: public/web
  via: apache
  cache: redis
  xdebug: true

excludes:
  - public
  - node_modules
  - vendor

services:
  database:
    type: mariadb:11.5
    portforward: true
    creds:
      database: wordpress
      user: wordpress
      password: password
    environment:
      ALLOW_EMPTY_PASSWORD: 'no'

  appserver:
    ssl: true
    sslExpose: false
    overrides:
      environment:
        COMPOSER_CACHE_DIR: "/app/.cache/composer" # Saves a lot of time if you need to rebuild
#    run_as_root:
#      - apt-get update -y
#      - apt-get install zip nano dos2unix -y
#    run:
#      - bash .lando/bin/setup-wordpress.sh

  node:
    type: node:22
    ssl: true
    sslExpose: false
    ports:
      - "3009:3009"
    scanner: false
#    run:
#      - npm config set cache /app/.cache/npm
#    command: tail -f /dev/null # Keep it running for faster command execution


  redis:
    type: redis:6
    portforward: 6379

  mailhog:
    ssl: true
    sslExpose: false
    type: mailhog
    portforward: true
    hogfrom:
      - appserver

  phpmyadmin:
    ssl: true
    sslExpose: false
    type: phpmyadmin:5.2
    hosts:
      - database

tooling:
#  wp:
#    service: appserver
#    dir: /app/web
  enable-redis:
    service: appserver
    cmd: |
      cd $LANDO_MOUNT/public
      wp config set WP_REDIS_HOST redis
      wp config set WP_REDIS_PORT 6379
      wp plugin install redis-cache --activate
      wp redis enable
  redis-cli:
    service: redis
  node:
    service: node
  npm:
    service: node
  sync-remount-to-local:
    service: appserver
    cmd: .lando/bin/sync-wp.sh
  bower:
    service: node
    cmd: node_modules/.bin/bower
```

vite.config.js
```
import * as fs from "fs"
import {resolve} from 'node:path'
import {defineConfig} from 'vite';
import liveReload from 'vite-plugin-live-reload';

export default defineConfig({
  plugins: [
    liveReload([
      __dirname + '/**/*.php',
    ]),
  ],
  base: process.env.NODE_ENV === 'development' ? '/' : 'dist',
  root: '.',
  build: {
    outDir: 'dist',
    emptyOutDir: true,
    manifest: 'manifest.json',
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'assets/scripts/main.js'),
        admin: resolve(__dirname, 'assets/scripts/admin.js'),
        style: resolve(__dirname, 'assets/styles/main.scss'),
      },
      output: {
        entryFileNames: '[name].[hash].js', // Add hash for better caching
        chunkFileNames: '[name].[hash].js',
        assetFileNames: '[name].[ext]',
        manualChunks(id) {
          if (id.includes('node_modules')) {
            return 'vendor'
          }
        }
      },
    },
  },
  css: {
    devSourcemap: true,
    preprocessorOptions: {
      scss: {
        includePaths: [
          resolve(__dirname, 'node_modules/bootstrap-sass/assets/stylesheets'),
          'node_modules',
        ],
      },
    },
  },
  server: {
    port: 3009,
    server: {
      https: false,
      host: true,
      port: 3009,
      hmr: {host: 'localhost', protocol: 'ws'},
    },
  }
});

```

Why doesn't Lando have any valuable tutorials on how to make things work?
Thera is supper significant infrastructure and any good info on how to do everything to work perfectly, so sad...
