### ISSUE TITLE
Tooling - Dynamic service commands enhancment

### ISSUE THREAD

**Issue by phpsa** [lando/core#44]
basic idea:
using your example:
```yaml
tooling:
  php-version:
    service: :service
    cmd: php -v
    options:
      service:
        default: appserver
        describe: Run php in different service
```

But switched to something more usefull like composer:

```yaml
tooling:
  composer:
    service: :service
    cmd: php -v
    options:
      service:
        default: appserver
        describe: Run composer in different service
```
Issue is that i need to trigger the correct composer based on the service:
currently core code looks for the dir in the tool -- which does not help,
could the method in the lando tooling utils do something like:

```node
exports.buildCommand = (app, command, service, user, env = {}, dir = undefined) => ({
  id: `${app.project}_${service}_1`,
  compose: app.compose,
  project: app.project,
  cmd: command,
  opts: {
    environment: getCliEnvironment(env),
    mode: 'attach',
    workdir: dir || getServicePath(service) || getContainerPath(app.root),
    user: (user === null) ? getUser(service, app.info) : user,
    services: _.compact([service]),
    hijack: false,
    autoRemove: true,
  },
});
```

Thereby reading the `dir` option on the service definition?
